# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=libreria-musical
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432 

  adminer:
    image: adminer
    ports:
      - 8080:8080