# Generated by Django 3.2.9 on 2021-11-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='fecha_salida',
            field=models.DateField(blank=True, verbose_name='Fecha de salida'),
        ),
        migrations.AlterField(
            model_name='album',
            name='genero',
            field=models.CharField(blank=True, max_length=200, verbose_name='Género'),
        ),
    ]
