# Generated by Django 3.2.9 on 2021-11-17 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0002_auto_20211117_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='canciones',
        ),
        migrations.AddField(
            model_name='cancion',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='musica.album'),
        ),
        migrations.AlterField(
            model_name='album',
            name='discografica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='musica.discografica'),
        ),
        migrations.AlterField(
            model_name='album',
            name='duracion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Duración total'),
        ),
        migrations.AlterField(
            model_name='album',
            name='fecha_salida',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de salida'),
        ),
    ]
