# Generated by Django 3.2.9 on 2021-11-17 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0003_auto_20211117_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='nombre',
            new_name='nombre_artista',
        ),
    ]
