# Generated by Django 3.2.9 on 2021-11-20 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0004_rename_nombre_artista_nombre_artista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discografica',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='album',
            name='discografica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='musica.discografica', verbose_name='Discográfica'),
        ),
    ]
