# Generated by Django 3.2.9 on 2021-11-21 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0005_auto_20211120_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='fecha_salida',
        ),
    ]
