# Generated by Django 3.2.9 on 2021-11-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0006_remove_album_fecha_salida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Album'},
        ),
    ]
