# Generated by Django 3.2.9 on 2021-11-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0008_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='file',
            field=models.ImageField(height_field='alto', upload_to='imagenes/', verbose_name='imagen', width_field='ancho'),
        ),
    ]
