# Generated by Django 3.2.9 on 2021-11-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0009_auto_20211124_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='img',
            field=models.URLField(blank=True),
        ),
    ]
