# Generated by Django 3.2.9 on 2021-11-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0010_album_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='img',
        ),
    ]
