# Generated by Django 3.2.9 on 2021-12-08 14:11

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0011_remove_album_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[240, 240], upload_to='imagenes'),
        ),
        migrations.AlterField(
            model_name='album',
            name='genero',
            field=models.CharField(choices=[('ROCK', 'Rock&Roll'), ('POP', 'Pop'), ('CLAS', 'Clásica'), ('RNB', 'Rhythm and Blues'), ('DISC', 'Disco'), ('COUN', 'Country'), ('JAZZ', 'Jazz'), ('REGG', 'Reggae'), ('FLAM', 'Flamenco'), ('BSO', 'Bandas Sonoras'), ('BAL', 'Baladas')], max_length=4),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='file',
            field=models.ImageField(height_field='alto', upload_to='imagenes', verbose_name='imagen', width_field='ancho'),
        ),
    ]
