# Generated by Django 3.2.9 on 2021-12-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0015_alter_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='cover'),
        ),
    ]
