# Generated by Django 3.2.9 on 2021-12-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0017_alter_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='not-found.png', null=True, upload_to='imagenes/'),
        ),
    ]
